### ISSUE TITLE
String range generates unexpected values beyond end character when using "z"

### ISSUE THREAD

**Issue by robertnisipeanu** [ptopczewski/range-generator#2]
When running the generator with starting character "Z" and ending "Z", it is expected that it returns back just "Z", however, the generator will return "Z", "AA", "AB", ..., "BA", ..."YZ".

That's because of the condition in the loop here: https://github.com/ptopczewski/range-generator/blob/1fcffcf6cdf33a3dd89fcc37b7b11b8e60429860/src/Services/Generator.php#L43

In PHP `"AA" < "Z"` evaluates to `true` so the loop doesn't stops after the first character generated (for reasons I don't know, it could be that it only compares the first letter, but then it wouldn't make sense on why it stops at "YZ" and doesn't continue with "ZZ" and "AAA").
I have reconstructed an example here: https://onlinephp.io/c/de19a
<img width="636" alt="image" src="https://github.com/user-attachments/assets/006a29ac-037a-4dff-85ef-e6e4865a4f38">

The fix I was able to come with is to add a condition check inside the loop and force break whenever getting to the end value: https://onlinephp.io/c/b9aec
<img width="582" alt="image" src="https://github.com/user-attachments/assets/e42e13d2-12c6-4e7a-9ef4-2da18db7104c">

I will create a PR with the above solution.

**Comment by ptopczewski** [comment]
Solved by @robertnisipeanu 's pull request
